

services:
  website:
    image: ghcr.io/shahirshamim/personal_website:latest
    container_name: personal_website
    restart: always
    networks:
      - tunnel_net
    labels:
      - "com.centurylinklabs.watchtower.scope=website"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.scope=website"
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - tunnel_net


  watchtower_website:
    image: containrrr/watchtower
    container_name: watchtower_website
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --interval 300 --cleanup
    environment:
      - WATCHTOWER_SCOPE=website

networks:
  tunnel_net:
    driver: bridge
